import type { Metadata } from "next";
import "../globals.css";
import TopBar from '@/components/shared/TopBar'
import BottomBar from '@/components/shared/BottomBar'
import SideBar from '@/components/shared/SideBar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='dark sm:flex sm:flex-col bg-[#0E0E0E]'>
        <TopBar />
        <main className='relative main-container w-[100%] flex mainsection'>
          <SideBar />
          <section className='flex-1 w-full sm:px-[16px]'>{children}</section>
        </main>
        <BottomBar />
      </body>
    </html>
  );
}
