POST http://localhost:3001/auth/signUp
Content-Type: application/json

{
  "email" : "beyblade@gmail.com",
  "password": "dhruvXyz"
}

###
POST http://localhost:3001/auth/signIn
Content-Type: application/json

{
  "email" : "shruvparmar@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:3001/users/create-user-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMwYmFjM2I3NzY4NWRlZDQ4MWZlNTQiLCJpYXQiOjE3MDcxNDAyMjUsImV4cCI6MTcwOTczMjIyNX0.MX-Hm7xJr5v9Gr7YeXSZbxaBvyTyHKmmnUPmLWgBHh8
Content-Type: application/json

{
  "name": "Dhruv",
  "enrollmentNumber": "2204030100805",
  "branchName": "cse",
  "semesterNumber": 4,
  "divisionName": "b",
  "isPrivate": true
}

###
POST http://localhost:3001/post/create-post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMxMTcwMmRhY2E3ZjgyZTQ3NjFjY2YiLCJpYXQiOjE3MDcxNTcxOTQsImV4cCI6MTcwOTc0OTE5NH0.FTFVwW_5eHVtrfoAtWW0fv06E1CRwztebMxE0bWvHRA
Content-Type: application/json

{
  "title": "Do you guys play genshin impact?",
  "imageUrl": "https://pbs.twimg.com/media/GE4khWFW0AAYBuI?format=jpg&name=4096x4096",
  "caption": "Hi guys meet the new character navia which I just unlocked",
  "location": "",
  "category": "friends",
  "postedBy": "65c11702daca7f82e4761ccf"
}

### 
POST http://localhost:3001/branches/create-branch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMwYmFjM2I3NzY4NWRlZDQ4MWZlNTQiLCJpYXQiOjE3MDcxNDAyMjUsImV4cCI6MTcwOTczMjIyNX0.MX-Hm7xJr5v9Gr7YeXSZbxaBvyTyHKmmnUPmLWgBHh8
Content-Type: application/json

{
  "branchName": "cse",
  "branchFullName": "computer-science-engineering",
  "numberOfSemesters": 8
}

###
GET http://localhost:3001/post/get-post?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWM0YTBhMDJlOWE5N2UzM2E5YTA0NjYiLCJpYXQiOjE3MDczODQ5OTIsImV4cCI6MTcwOTk3Njk5Mn0.FBG__DfuLbr-hrGdGt4qEpVFw3jP5hB1LxVUU3wF-VM



###
GET http://localhost:3001/branches/get-branch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMwYmFjM2I3NzY4NWRlZDQ4MWZlNTQiLCJpYXQiOjE3MDcxNDAyMjUsImV4cCI6MTcwOTczMjIyNX0.MX-Hm7xJr5v9Gr7YeXSZbxaBvyTyHKmmnUPmLWgBHh8

###

GET http://localhost:3001/branches/get-semester?branchName=cse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMwYmFjM2I3NzY4NWRlZDQ4MWZlNTQiLCJpYXQiOjE3MDcxNDAyMjUsImV4cCI6MTcwOTczMjIyNX0.MX-Hm7xJr5v9Gr7YeXSZbxaBvyTyHKmmnUPmLWgBHh8



###
POST http://localhost:3001/post/comment/like-comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMwYmFjM2I3NzY4NWRlZDQ4MWZlNTQiLCJpYXQiOjE3MDcxNDAyMjUsImV4cCI6MTcwOTczMjIyNX0.MX-Hm7xJr5v9Gr7YeXSZbxaBvyTyHKmmnUPmLWgBHh8
Content-Type: application/json

{
  "commentId": "65c0e776a47b51effeaf6c2f",
  "userID": "65c0bac3b77685ded481fe54"
}

###
POST http://localhost:3001/post/comment/reply-comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMxMTcwMmRhY2E3ZjgyZTQ3NjFjY2YiLCJpYXQiOjE3MDcxNjcxNDgsImV4cCI6MTcwOTc1OTE0OH0.UfGAK5JLQr3fGFkRw3aSRHbrDBTZKywS-eEQlsk1kp8
Content-Type: application/json

{
  "parentCommentId": "65c12796f85aafdfb2309f21",
  "postId": "65c1276af85aafdfb2309f1c",
  "repliedUserId": "65c14a8c7f2ff4f179511177",
  "commentText": "hey she's my wifeeeee!!!",
  "postedBy": "65c11702daca7f82e4761ccf"
}

###
POST http://localhost:3001/post/comment/reply-comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWMxNGE4YzdmMmZmNGYxNzk1MTExNzciLCJpYXQiOjE3MDcxNjcwODQsImV4cCI6MTcwOTc1OTA4NH0.rgdMgb4TOVxAgz9CJiN2OwxjpMibFS99asrNMBrrTWA
Content-Type: application/json

{
  "parentCommentId": "65c12796f85aafdfb2309f21",
  "postId": "65c1276af85aafdfb2309f1c",
  "repliedUserId": "65c11702daca7f82e4761ccf",
  "commentText": "Yupp",
  "postedBy": "65c14a8c7f2ff4f179511177"
}

###
GET http://localhost:3001/auth/check-user?userID


###
GET http://localhost:3001/users/get-user-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA3ODIxNTExLCJleHAiOjE3MTA0MTM1MTF9.HSY0ffG13gIzNHkuelbfnGzGT-VKnJ-fJTCiIU-c5F0

###
GET http://localhost:3001/users/get-user-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA3ODIxNTExLCJleHAiOjE3MTA0MTM1MTF9.HSY0ffG13gIzNHkuelbfnGzGT-VKnJ-fJTCiIU-c5F0


###
GET http://localhost:3001/users/get-user-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiNDlmZjM5MTkzMzNhYTM4MDcyMWIiLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjRhNzczOTE5MzMzYWEzODA3MjI4IiwidXNlcm5hbWUiOiJ5YWVNaWtvIiwiZW1haWwiOiJ5YWVtaWtvQGdtYWlsLmNvbSIsImlhdCI6MTcwNzgyNDMwMCwiZXhwIjoxNzEwNDE2MzAwfQ.ifXu0q8xQ333Pvh2lqcXhVTduNV1KpFDILjukcFcRqE

###
POST http://localhost:3001/post/like-post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWM3NzFiOWIwNmU5ZjMzNDVmMTRjNWQiLCJ1c2VyUHJvZmlsZUlkIjoiNjVjNzcyMDZiMDZlOWYzMzQ1ZjE0YzZhIiwiaWF0IjoxNzA3NTcwMzc4LCJleHAiOjE3MTAxNjIzNzh9.GE2Qi7FGdoGxy925wRkJaGdZfplOWG5NYUiwBc5u1rY
Content-Type: application/json

{
  "userProfileID": "65c77206b06e9f3345f14c6a",
  "postId": "65c7797f5b1f748a4a27d981"
}

###
GET http://localhost:3001/users/users-of-division
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWM3NzFiOWIwNmU5ZjMzNDVmMTRjNWQiLCJ1c2VyUHJvZmlsZUlkIjoiNjVjNzcyMDZiMDZlOWYzMzQ1ZjE0YzZhIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA3NzMwNDAxLCJleHAiOjE3MTAzMjI0MDF9.z6uQoh7L6ujf0LTOAPBPhAWLGNruygtlVNp0LA24nRk

###
GET http://localhost:3001/users/userprofile?username=yae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA3ODIxNTExLCJleHAiOjE3MTA0MTM1MTF9.HSY0ffG13gIzNHkuelbfnGzGT-VKnJ-fJTCiIU-c5F0


### 
POST http://localhost:3001/users/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA3OTA4NDk1LCJleHAiOjE3MTA1MDA0OTV9.YrTa0hcBfbC5VU3w_KENTAOnWZfse369diak6FaRj5s

{
  "userId": "65cb2eacb8be06b7dd50272f",
  "userToFollowId": "65cb4a773919333aa3807228"
}


###
GET http://localhost:3001/users/isFollowing?userToFollowId=65cb4a773919333aa3807228
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA4MDE0NTcyLCJleHAiOjE3MTA2MDY1NzJ9.EjVilkuEAvEqQupOyh8gSJSp_PsW39MxXT5S0FVLYhA


###
POST http://localhost:3001/users/unFollow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA4MDE5MjUwLCJleHAiOjE3MTA2MTEyNTB9.4nKvRqcTRmiRoNWO2G3OsXPh1rLVPXLQEGZfbnHKSkU

{
  "userToUnfollowId": "65cc9cc009364e2017d5e126"
}


###
GET http://localhost:3001/post?postId=65cb2f35b8be06b7dd502741
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA4MDE5MjUwLCJleHAiOjE3MTA2MTEyNTB9.4nKvRqcTRmiRoNWO2G3OsXPh1rLVPXLQEGZfbnHKSkU


###
POST http://localhost:3001/post/comment/create-comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWM3MzA2YjJhZmE1YjM2YzRlZmI2NjkiLCJ1c2VyUHJvZmlsZUlkIjoiNjVjNzMxNWIyYWZhNWIzNmM0ZWZiNjdjIiwiaWF0IjoxNzA3NTUzMTE1LCJleHAiOjE3MTAxNDUxMTV9.MYXhw87wj6VYLZto0QdXQ4KdQNk5fIUyo65Vkuyb3KY
Content-Type: application/json

{
  "postId": "65cb5a577af3c38b30193f3b",
  "commentText": "Y'all stay away she's my valentine for webdevelopment",
  "postedBy": "65cb2eacb8be06b7dd50272f"
}


###
GET http://localhost:3001/post/comment/sub-comment?parentCommentId=65d3436763d7983f7924ed7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwidXNlcm5hbWUiOiJ5YWVEaHJ1diIsImVtYWlsIjoic2hydXZwYXJtYXJAZ21haWwuY29tIiwiaWF0IjoxNzA4MzQ0MjE4LCJleHAiOjE3MTA5MzYyMTh9.LDEMnJ2QF9k4fstlwC0F5o4o1-YYtH3SrjcMfMtz8kE