GET http://localhost:3001/classroom/updates/65f0461d22ccc9e0e0deed75?page=0&limit=1
Content-Type: application/json
Cookies: classX_user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWNiMmIzNjNlYjVlZDJlZDYyNzgwNDciLCJ1c2VyUHJvZmlsZUlkIjoiNjVjYjJlYWNiOGJlMDZiN2RkNTAyNzJmIiwiaWF0IjoxNzA5ODc5MjMwLCJleHAiOjE3MTI0NzEyMzB9.NwCO0Tcfp_m_OdaOxNmWa0W1oBjY3WgQLTLQI9iOvFk
