POST http://localhost:3001/auth/signUp
Content-Type: application/json

{
  "email" : "karina@gmail.com",
  "password": "karinaDhruv"
}

###
POST http://localhost:3001/auth/signIn
Content-Type: application/json

{
  "email" : "karina@gmail.com",
  "password": "karinaDhruv"
}

###
POST http://localhost:3001/users/create-user-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NWJhYTU2YzFjMTJjM2MyYmQwYWZjY2EiLCJpYXQiOjE3MDY3MzA4ODIsImV4cCI6MTcwOTMyMjg4Mn0.TpCLVcbmy1GlmTwfk6Oa-VG1IKQaZb9PkEgxVHGucqQ
Content-Type: application/json

{
  "name": "Dhruv",
  "enrollmentNumber": "2204030100775",
  "branchName": "bca",
  "semesterNumber": 4,
  "divisionName": "a",
  "isPrivate": true
}
